In [4]:
import pandas as pd

df = pd.read_csv("../data/APL_Logistics.csv", encoding="latin1")

print("Shape:", df.shape)

df.head()

Shape: (180519, 40)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Name,Product Price,Shipping Mode
0,DEBIT,6,4,159.69,472.45,Late delivery,1,9,Cardio Equipment,Brownsville,...,5,499.95,472.45,159.69,South Asia,Maharashtra,COMPLETE,Nike Men's Free 5.0+ Running Shoe,99.99,Standard Class
1,DEBIT,4,4,48.71,167.96,Shipping on time,0,29,Shop By Sport,Littleton,...,5,199.95,167.96,48.71,Central America,Cortés,ON_HOLD,Under Armour Girls' Toddler Spine Surge Runni,39.99,Standard Class
2,DEBIT,4,4,87.36,181.99,Shipping on time,0,48,Water Sports,Littleton,...,1,199.99,181.99,87.36,Central America,Cortés,ON_HOLD,Pelican Sunstream 100 Kayak,199.99,Standard Class
3,DEBIT,6,4,-41.89,175.99,Late delivery,1,48,Water Sports,Littleton,...,1,199.99,175.99,-41.89,East of USA,Nueva York,COMPLETE,Pelican Sunstream 100 Kayak,199.99,Standard Class
4,DEBIT,6,4,10.00,40.00,Late delivery,1,24,Women's Apparel,Littleton,...,1,50.00,40.00,10.00,East of USA,Nueva York,COMPLETE,Nike Men's Dri-FIT Victory Golf Polo,50.00,Standard Class

In [5]:
df.head()
df.shape
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  str
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  str
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  str
 9   Customer City                  180519 non-null  str
 10  Customer Country               180519 non-null  str
 11  Customer Fname                 180519 non-null  str
 12  Customer Id                    180519 non-null  int64
 13  Customer Lname                 180511 non-null  str
 14  Customer Segment               180519 non-null  str
 15  Customer State                 180519 non-null  str
 16  Customer Street                180519 non-null  str
 17  Customer Zipcode               180516 non-null  float64
 18  Department Id                  180519 non-null  int64
 19  Department Name                180519 non-null  str
 20  Latitude                       180519 non-null  float64
 21  Longitude                      180519 non-null  float64
 22  Market                         180519 non-null  str
 23  Order City                     180519 non-null  str
 24  Order Country                  180519 non-null  str
 25  Order Customer Id              180519 non-null  int64
 26  Order Item Discount            180519 non-null  float64
 27  Order Item Discount Rate       180519 non-null  float64
 28  Order Item Product Price       180519 non-null  float64
 29  Order Item Profit Ratio        180519 non-null  float64
 30  Order Item Quantity            180519 non-null  int64
 31  Sales                          180519 non-null  float64
 32  Order Item Total               180519 non-null  float64
 33  Order Profit Per Order         180519 non-null  float64
 34  Order Region                   180519 non-null  str
 35  Order State                    180519 non-null  str
 36  Order Status                   180519 non-null  str
 37  Product Name                   180519 non-null  str
 38  Product Price                  180519 non-null  float64
 39  Shipping Mode                  180519 non-null  str
dtypes: float64(13), int64(8), str(19)
memory usage: 90.2 MB

Type                             0
Days for shipping (real)         0
Days for shipment (scheduled)    0
Benefit per order                0
Sales per customer               0
Delivery Status                  0
Late_delivery_risk               0
Category Id                      0
Category Name                    0
Customer City                    0
Customer Country                 0
Customer Fname                   0
Customer Id                      0
Customer Lname                   8
Customer Segment                 0
Customer State                   0
Customer Street                  0
Customer Zipcode                 3
Department Id                    0
Department Name                  0
Latitude                         0
Longitude                        0
Market                           0
Order City                       0
Order Country                    0
Order Customer Id                0
Order Item Discount              0
Order Item Discount Rate         0
Order Item Product Price         0
Order Item Profit Ratio          0
Order Item Quantity              0
Sales                            0
Order Item Total                 0
Order Profit Per Order           0
Order Region                     0
Order State                      0
Order Status                     0
Product Name                     0
Product Price                    0
Shipping Mode                    0
dtype: int64

In [7]:
df.shape

(180519, 40)

In [9]:
### Dataset Size

# The dataset contains:

# - 180,519 rows (orders)
# - 40 columns (features)

# This provides sufficient data for exploratory analysis and machine learning model development.

In [10]:
df["Late_delivery_risk"].value_counts()

Late_delivery_risk
1    98977
0    81542
Name: count, dtype: int64

In [11]:
df["Late_delivery_risk"].value_counts(normalize=True) * 100

Late_delivery_risk
1    54.829132
0    45.170868
Name: proportion, dtype: float64

In [12]:
### Target Variable Analysis

# Target Variable: Late_delivery_risk

# Class Distribution:

# - Late Deliveries (1): 98,977 orders
# - On-Time Deliveries (0): 81,542 orders

# Observation:

# The target variable appears relatively balanced, with slightly more late deliveries than on-time deliveries. This is favorable for machine learning model training and evaluation.

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
### Duplicate Records Analysis

# Number of duplicate rows: 0

# Observation:

# No duplicate records were found in the dataset. No duplicate removal is required.

In [16]:
df.isnull().sum().sort_values(ascending=False)

Customer Lname                   8
Customer Zipcode                 3
Type                             0
Days for shipping (real)         0
Sales per customer               0
Delivery Status                  0
Days for shipment (scheduled)    0
Benefit per order                0
Category Id                      0
Late_delivery_risk               0
Customer Country                 0
Category Name                    0
Customer Fname                   0
Customer Id                      0
Customer Segment                 0
Customer City                    0
Customer State                   0
Customer Street                  0
Department Id                    0
Department Name                  0
Latitude                         0
Longitude                        0
Market                           0
Order City                       0
Order Country                    0
Order Customer Id                0
Order Item Discount              0
Order Item Discount Rate         0
Order Item Product Price         0
Order Item Profit Ratio          0
Order Item Quantity              0
Sales                            0
Order Item Total                 0
Order Profit Per Order           0
Order Region                     0
Order State                      0
Order Status                     0
Product Name                     0
Product Price                    0
Shipping Mode                    0
dtype: int64

In [ ]:
### Missing Values Analysis

# Columns with Missing Values:

# - Customer Lname: 8
# - Customer Zipcode: 3

# Observation:

# The dataset contains very few missing values. Missing data accounts for a negligible percentage of the dataset and can be handled easily during preprocessing.

# Most columns contain complete information.

In [17]:
df.dtypes.value_counts()

str        19
float64    13
int64       8
Name: count, dtype: int64

In [18]:
### Data Types Analysis

# The dataset contains:

# - 19 categorical features
# - 13 float features
# - 8 integer features

# Observation:

# The dataset contains a mix of numerical and categorical variables, making it suitable for both statistical analysis and machine learning modeling.

# Categorical variables will require encoding before model training.

In [19]:
df[["Delivery Status", "Order Status"]].head()

    Delivery Status Order Status
0     Late delivery     COMPLETE
1  Shipping on time      ON_HOLD
2  Shipping on time      ON_HOLD
3     Late delivery     COMPLETE
4     Late delivery     COMPLETE

In [ ]:
### Data Leakage Analysis

# Potential Leakage Columns Identified:

# 1. Delivery Status
# 2. Days for shipping (real)

# Reason:

# These columns contain information that becomes available only after shipment completion and are strongly related to the target variable.

# Using these features during model training would cause data leakage and produce unrealistically high model performance.

# These columns should be excluded from machine learning modeling.

In [20]:
# Numerical columns
num_cols = df.select_dtypes(include=['int64','float64']).columns

# Categorical columns
cat_cols = df.select_dtypes(include=['object']).columns

print("Numerical Columns:", len(num_cols))
print("Categorical Columns:", len(cat_cols))

Numerical Columns: 21
Categorical Columns: 19

C:\Users\parve\AppData\Local\Temp\ipykernel_32448\3967974092.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include=['object']).columns